.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitvault_qt test_bitvault_qt
clean: FORCE
	$(MAKE) -C .. bitvault_qt_clean test_bitvault_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitvault_qt_check
bitvault-qt bitvault-qt.exe: FORCE
	 $(MAKE) -C .. bitvault_qt
apk: FORCE
	$(MAKE) -C .. bitvault_qt_apk
