dist_man1_MANS=

if BUILD_BITVAULTD
  dist_man1_MANS+=bitvaultd.1
endif

if ENABLE_QT
  dist_man1_MANS+=bitvault-qt.1
endif

if BUILD_BITVAULT_CLI
  dist_man1_MANS+=bitvault-cli.1
endif

if BUILD_BITVAULT_TX
  dist_man1_MANS+=bitvault-tx.1
endif

if BUILD_BITVAULT_UTIL
  dist_man1_MANS+=bitvault-util.1
endif

if ENABLE_WALLET
if BUILD_BITVAULT_WALLET
  dist_man1_MANS+=bitvault-wallet.1
endif
endif
