#!/usr/bin/env python3
"""
Update BIP341 test vectors with correct BitVault bech32 addresses
based on the addresses generated by the test
"""

import json

# Map of incorrect addresses to correct ones from test output
address_corrections = {
    "dgb1p2wsldez5mud2yam29q22wgfh9439spgduvct83k3pm50fcxa5dps59h4z5": "dgb1p2wsldez5mud2yam29q22wgfh9439spgduvct83k3pm50fcxa5dpsf0nhat",
    "dgb1pz37fc4cn9ah8anwm4xqqhvxygjf9rjf2resrw8h8w4tmvcs0863sa2e586": "dgb1pz37fc4cn9ah8anwm4xqqhvxygjf9rjf2resrw8h8w4tmvcs0863sqqakc9",
    "dgb1punvppl2stp38f7kwv2u2spltjuvuaayuqsthe34hd2dyy5w4g58qqfuag5": "dgb1punvppl2stp38f7kwv2u2spltjuvuaayuqsthe34hd2dyy5w4g58qarclht",
    "dgb1pwyjywgrd0ffr3tx8laflh6228dj98xkjj8rum0zfpd6h0e930h6saqxrrm": "dgb1pwyjywgrd0ffr3tx8laflh6228dj98xkjj8rum0zfpd6h0e930h6sq2zpuy",
    "dgb1pwl3s54fzmk0cjnpl3w9af39je7pv5ldg504x5guk2hpecpg2kgsqaqstjq": "dgb1pwl3s54fzmk0cjnpl3w9af39je7pv5ldg504x5guk2hpecpg2kgsqq25fdl",
    "dgb1pjxmy65eywgafs5tsunw95ruycpqcqnev6ynxp7jaasylcgtcxczs6n332e": "dgb1pjxmy65eywgafs5tsunw95ruycpqcqnev6ynxp7jaasylcgtcxczs8e4n4x",
    "dgb1pw5tf7sqp4f50zka7629jrr036znzew70zxyvvej3zrpf8jg8hqcssyuewe": "dgb1pw5tf7sqp4f50zka7629jrr036znzew70zxyvvej3zrpf8jg8hqcsdwcm3x"
}

def update_addresses_in_json(filename):
    """Update addresses in JSON file"""
    with open(filename, 'r') as f:
        data = json.load(f)
    
    def update_value(value):
        """Recursively update addresses in JSON"""
        if isinstance(value, str):
            # Check if this is an address that needs correction
            if value in address_corrections:
                print(f"Updating: {value} -> {address_corrections[value]}")
                return address_corrections[value]
            return value
        elif isinstance(value, dict):
            return {k: update_value(v) for k, v in value.items()}
        elif isinstance(value, list):
            return [update_value(item) for item in value]
        else:
            return value
    
    # Update the data
    updated_data = update_value(data)
    
    # Write back
    with open(filename, 'w') as f:
        json.dump(updated_data, f, indent=4)
    
    print(f"Updated {filename}")

if __name__ == "__main__":
    update_addresses_in_json("src/test/data/bip341_wallet_vectors.json")