description "BitVault Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BITVAULTD_BIN="/usr/bin/bitvaultd"
env BITVAULTD_USER="bitvault"
env BITVAULTD_GROUP="bitvault"
env BITVAULTD_PIDDIR="/var/run/bitvaultd"
# upstart can't handle variables constructed with other variables
env BITVAULTD_PIDFILE="/var/run/bitvaultd/bitvaultd.pid"
env BITVAULTD_CONFIGFILE="/etc/bitvault/bitvault.conf"
env BITVAULTD_DATADIR="/var/lib/bitvaultd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # bitvaultd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BITVAULTD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bitvaultd."
        echo "The setting must appear in $BITVAULTD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BitVault Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BITVAULTD_PIDDIR"
    chmod 0755 "$BITVAULTD_PIDDIR"
    chown $BITVAULTD_USER:$BITVAULTD_GROUP "$BITVAULTD_PIDDIR"
    chown $BITVAULTD_USER:$BITVAULTD_GROUP "$BITVAULTD_CONFIGFILE"
    chmod 0660 "$BITVAULTD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BITVAULTD_PIDFILE" \
    --chuid $BITVAULTD_USER:$BITVAULTD_GROUP \
    --exec "$BITVAULTD_BIN" \
    -- \
    -pid="$BITVAULTD_PIDFILE" \
    -conf="$BITVAULTD_CONFIGFILE" \
    -datadir="$BITVAULTD_DATADIR" \
    -disablewallet \
    -daemon

